export const ACTION_ADD_ENEMY = 'ADD_ENEMY';
export const ACTION_ADD_PATHWAY_COORDINATE = 'ADD_COORD';
export const ACTION_CHOOSE_LEVEL = 'LEVEL';
export const ACTION_CHOOSE_PARTY = 'PARTY';
export const ACTION_NAVIGATE_TO_SCENE = 'NAV';
export const ACTION_SET_DRAFT_LEVEL_MAX_ENEMIES = 'DRAFT_MAX_ENEMIES';
export const ACTION_SET_DRAFT_LEVEL_MODE = 'DRAFT_MODE';
export const ACTION_SET_NICKAME = 'NICKNAME';
